# Generated by Django 3.2.7 on 2021-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FBATransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('type', models.TextField(blank=True, max_length=32, null=True)),
                ('order_id', models.TextField(blank=True, max_length=64, null=True)),
                ('sku', models.TextField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_state', models.TextField(blank=True, max_length=32, null=True)),
                ('order_city', models.TextField(blank=True, max_length=32, null=True)),
                ('order_postal', models.TextField(blank=True, max_length=32, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
            options={
                'db_table': 'fba_transactions',
            },
        ),
    ]
